export default {
  DOC_VIEW_GET_CDR_FAILURE: 'DOC_VIEW_GET_CDR_FAILURE',
  COMPLETE_WORD_COUNT_QUERY: 'COMPLETE_WORD_COUNT_QUERY',
  COMPLETE_DOC_VIEW_AGGREGATIONS_QUERY: 'COMPLETE_DOC_VIEW_AGGREGATIONS_QUERY',
  COMPLETE_DOC_VIEW_FACETS_QUERY: 'COMPLETE_DOC_VIEW_FACETS_QUERY',
  SET_DOCUMENT_VIEW: 'SET_DOCUMENT_VIEW',
  COMPLETE_GET_CDR: 'COMPLETE_GET_CDR',
  DOC_VIEW_CLEAR_STATE: 'DOC_VIEW_CLEAR_STATE',
};
