export default {
  SECTION_COMPONENT: 'SECTION_COMPONENT',
  TAG_VALUES_COMPONENT: 'TAG_VALUES_COMPONENT',
  TAG_TYPES_COMPONENT: 'TAG_TYPES_COMPONENT',
  FACET_COMPONENT: 'FACET_COMPONENT',
  FACET_CONFIDENCE_FILTER_COMPONENT: 'FACET_CONFIDENCE_COMPONENT',
  FACET_CONFIDENCE_AVG_COMPONENT: 'FACET_CONFIDENCE_AVG_COMPONENT',
  METADATA_KEYWORD_COMPONENT: 'METADATA_KEYWORD_COMPONENT',
  METADATA_NUMBER_COMPONENT: 'METADATA_NUMBER_COMPONENT',
  METADATA_DATE_COMPONENT: 'METADATA_DATE_COMPONENT',
  TAG_COMPONENT: 'TAG_COMPONENT",',
};
