export default {
  UPDATE_ROOT_COMPONENT_MAP: 'UPDATE_ROOT_COMPONENT_MAP',
  COMPLETE_TAG_TYPE_QUERY: 'COMPLETE_TAG_TYPE_QUERY',
  COMPLETE_FACET_QUERY: 'COMPLETE_FACET_QUERY',
  ADD_COMPONENT: 'ADD_COMPONENT',
  REMOVE_COMPONENT: 'REMOVE_COMPONENT',
  UPDATE_COMPONENT_BOOL_TYPE: 'UPDATE_COMPONENT_BOOL_TYPE',
  TOGGLE_COMPONENT_EDITED: 'TOGGLE_COMPONENT_EDITED',
  UPDATE_COMPONENT_STATE: 'UPDATE_COMPONENT_STATE',
};
