export default {
  CORPUS_VIEW_UPDATE_ALL_AGGS: 'CORPUS_VIEW_UPDATE_ALL_AGGS',
  CORPUS_VIEW_UPDATE_COMPONENT_STATE: 'CORPUS_VIEW_UPDATE_COMPONENT_STATE',
  CORPUS_VIEW_UPDATE_COMPONENT: 'CORPUS_VIEW_UPDATE_COMPONENT',
  CORPUS_VIEW_ADD_COMPONENT: 'CORPUS_VIEW_ADD_COMPONENT',
  CORPUS_VIEW_REMOVE_COMPONENT: 'CORPUS_VIEW_REMOVE_COMPONENT',
  CORPUS_VIEW_UPDATE_COMPONENT_MAP: 'CORPUS_VIEW_UPDATE_COMPONENT_MAP',
};
