const uploadFilesTypes = {
  SET_UPLOAD_FILES: 'SET_UPLOAD_FILES',
  SET_UPLOAD_METADATA: 'SET_UPLOAD_METADATA',
  START_UPLOAD_FILES: 'START_UPLOAD_FILES',
  FINISH_UPLOAD_FILES: 'FINISH_UPLOAD_FILES',
  SET_UPLOAD_PROGRESS: 'SET_UPLOAD_PROGRESS',
  SUCCESS_UPLOAD_FILE: 'SUCCESS_UPLOAD_FILE',
  SUCCESS_UPLOAD_ZIP_FILE: 'SUCCESS_UPLOAD_ZIP_FILE',
  FAILURE_UPLOAD_FILE: 'FAILURE_UPLOAD_FILE',
  START_POLL_STATUS: 'START_POLL_REQUEST',
  COMPLETE_POLL_STATUS: 'COMPLETE_POLL_STATUS',
  UPDATE_DOCUMENT_STATUS: 'UPDATE_DOCUMENT_STATUS',
  START_POLLING: 'START_POLLING',
  STOP_POLLING: 'STOP_POLLING',
  UPDATE_DOCUMENT_STATUS_ALL: 'UPDATE_DOCUMENT_STATUS_ALL',
  SET_POLL_WINDOW: 'SET_POLL_WINDOW',
  UPDATE_LABELS_TEXT: 'UPDATE_LABELS_TEXT',
};

export default uploadFilesTypes;
