FROM twosixlabsdart/java-fatjar-runner:latest

LABEL maintainer="john.hungerford@twosixlabs.com"

ENV SCALA_VERSION '2.12'

ENV JAVA_OPTS="-Xms1g -Xmx2g -XX:+UseG1GC"

COPY ./backend/utilities/target/scala-$SCALA_VERSION/*assembly*.jar $APP_DIR

RUN chmod -R 755 /opt/app

ENTRYPOINT ["/opt/app/run-jar.sh"]
