export default {
  UPDATE_SEARCH_QUERIES: 'UPDATE_SEARCH_QUERIES',
  START_COUNT: 'START_COUNT',
  COMPLETE_COUNT: 'COMPLETE_COUNT',
  START_SEARCH: 'START_SEARCH',
  COMPLETE_SEARCH: 'COMPLETE_SEARCH',
  SEARCH_ERROR: 'SEARCH_ERROR',
  TOGGLE_SEARCH_RESULT_EXPANSION: 'TOGGLE_SEARCH_RESULT_EXPANSION',
  COMPLETE_AGGREGATIONS_QUERY: 'COMPLETE_AGGREGATIONS_QUERY',
  COMPLETE_FACETS_QUERY: 'COMPLETE_FACETS_QUERY',
  COMPLETE_AGG_SEARCH: 'COMPLETE_AGG_SEARCH',
  CLEAR_CORPUS_OVERVIEW_AGG_QUERIES: 'CLEAR_CORPUS_OVERVIEW_AGG_QUERIES',
  ADD_CORPUS_OVERVIEW_AGG_QUERIES: 'ADD_CORPUS_OVERVIEW_AGG_QUERIES',
};
