export default {
  COMPLETE_GET_FACET_IDS: 'COMPLETE_GET_FACET_IDS',
  COMPLETE_GET_TAG_IDS: 'COMPLETE_GET_TAG_IDS',
  COMPLETE_GET_FIELD_IDS: 'COMPLETE_GET_FIELD_IDS',
  COMPLETE_GET_TAG_TYPES: 'COMPLETE_GET_TAG_TYPES',
};
