export default {
  HIGHLIGHT_EXTRACTION_TAGS: 'HIGHLIGHT_EXTRACTION_TAGS',
  REMOVE_EXTRACTION_TAGS_HIGHLIGHT: 'REMOVE_EXTRACTION_TAGS_HIGHLIGHT',
  EXPAND_TAG_TYPE: 'EXPAND_TAG_TYPE',
  UN_EXPAND_TAG_TYPE: 'UNEXPAND_TAG_TYPE',
  EXPAND_EXTRACTION_COMPONENT: 'EXPAND_EXTRACTION_COMPONENT',
  UN_EXPAND_EXTRACTION_COMPONENT: 'UN_EXPAND_EXTRACTION_COMPONENT',
  REGISTER_TAG_TYPE: 'REGISTER_TAG_TYPE',
  SET_TAG_STATE: 'SET_TAG_STATE',
};
