export default {
  SET_PDF_PAGE_NUMBER: 'SET_PDF_PAGE_NUMBER',
  SET_PDF_NUM_PAGES: 'SET_PDF_NUM_PAGES',
  SET_PDF_SCALE: 'SET_PDF_SCALE',
  PDF_LOADED: 'PDF_LOADED',
  COMPLETE_GET_RAW: 'COMPLETE_GET_RAW',
};
