export default {
  FOCUS_TAG: 'FOCUS_TAG',
  UNFOCUS_TAG: 'UNFOCUS_TAG',
  HOVER_TAG: 'HOVER_TAG',
  UNHOVER_TAG: 'UNHOVER_TAG',
  COMPLETE_SCROLL_TO_INDEX: 'COMPLETE_SCROLL_TO_INDEX',
  SET_SCROLL_TO_VIEW: 'SET_SCROLL_TO_VIEW',
  COMPLETE_SCROLL_TO: 'COMPLETE_SCROLL_TO',
  CLEAR_CDR_VIEW: 'CLEAR_CDR_VIEW',
  SET_CDR_TEXT_ARRAY: 'SET_CDR_TEXT_ARRAY',
};
