import settings from './settings';

export const {
  API_URL_BASE,
  RAW_DOC_URL,
  RAW_DOC_SOURCE,
} = settings;

export const DEFAULT_SEARCH_PAGE_SIZE = settings.DEFAULT_SEARCH_PAGE_SIZE || 20;
export const DEFAULT_TAG_RESULTS_PAGE_SIZE = settings.DEFAULT_TAG_RESULTS_PAGE_SIZE || 18;
export const DEFAULT_TAG_RESULTS_PAGES_RETRIEVED = settings.DEFAULT_TAG_RESULTS_PAGES_RETRIEVED
  || 10;
export const DEFAULT_TAG_RESULTS_QUERIED = DEFAULT_SEARCH_PAGE_SIZE
  * DEFAULT_TAG_RESULTS_PAGES_RETRIEVED;
