name: Build and Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SBT_OPTS: "-Xmx4G -Xss2M"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and Test
        run: sbt compileApp test

  publish-to-sonatype:
    if: ${{ github.ref == 'refs/heads/DART-1354-build-publish-github' || startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    env:
      SBT_OPTS: "-Xmx4G -Xss2M"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: publish-to-sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish-to-docker-hub:
    if: ${{ github.ref == 'refs/heads/DART-1354-build-publish-github' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: build
    env:
      SBT_OPTS: "-Xmx4G -Xss2M"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build and Push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: make docker-push

  tag-release:
    if: ${{ github.ref == 'refs/heads/DART-1354-build-publish-github' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: twosixlabs-dart/dart-tag-release@v3.0.20
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
